version: '3.4'

services:
  frontend_prod:
    build:
      context: schedule-frontend
      dockerfile: prod.dockerfile
    ports:
     - '80:80'
    expose:
     - '80'
    depends_on:
      - backend_prod
    networks:
      - frontend 

  database_prod:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=schedule-app"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  backend_prod:
    build:
      context: schedule-backend
      dockerfile: prod.dockerfile
    working_dir: /usr/src/java-code
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on: 
      - database_prod
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/schedule-app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend
      - frontend

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: